### ISSUE TITLE
Create architecture diagram

### ISSUE THREAD

**Issue by DOM-C1** [DOM-C1/Climate-Monitor#2]
## Description
Create a diagram representing the project architecture, aim to have a simple and cost effective solution. Add the resulting diagram to `README.md`.

## Relevant Files
- `README.md`

**Comment by DKWeeto** [comment]
![Image](https://github.com/DOM-C1/Climate-Monitor/assets/153939350/6df9f606-c3d1-4178-b5ee-913ee8c77500)
