### ISSUE TITLE
Transform data

### ISSUE THREAD

**Issue by DKWeeto** [DOM-C1/Climate-Monitor#5]
## Description
The 'T' in the ETL script, transform data into useable dataframe, remove bad or faulty data

## User Story

As an engineer, I need to clean and tranform the data in order to upload it to the database

## Output Files
- `ETL_pipeline/transform.py`

**Comment by DOM-C1** [comment]
Where are we pulling in this data? what data are you talking about? RDS, API? not clear

**Comment by DKWeeto** [comment]
done
